[show_env]
temperature = { split = { pattern = "Temp:", limit_keyword = "Normal", regex = false } }
["show env all"]
temperature = { multi_pattern = { pattern = "Temp:.+Normal", regex = true } }
["show env all"]
temperature = { multi_pattern = { pattern = "Temp:\\s*\\S+\\s+\\S+\\s+Normal", regex = true } }
