[show_env]
temperature = { split = { pattern = "Temp:", limit_keyword = "Normal", regex = false } }
["show env all"]
temperature = { multi_pattern = { pattern = "Temp:.+Normal", regex = true } }
["show env all"]
temperature = { multi_pattern = { pattern = "Temp:\\s*\\S+\\s+\\S+\\s+Normal", regex = true } }
["show env all"]
temperature = { 
	multi_pattern = { 
		pattern = "Temp:.*", 
		regex = true,
		compare_range = [0, 3]  # Temp: から Normal までの4つの項目を比較
	} 
}
[
"flexible_comparison"
]
route_comparison = { 
	flexible_pattern = {
		start_keyword = "\\d+\\.\\d+\\.\\d+\\.\\d+",  # IPアドレスのパターン
		end_keyword = "(?=\\d+\\.\\d+\\.\\d+\\.\\d+|$)",  # 次のIPアドレスまたは行末
		compare_range = [1, -1],  # IPアドレス以降のすべての情報を比較
		regex = true
	}
}
[
"routing_table"
]
ip_route_comparison = { 
    flexible_pattern = {
        start_keyword = "10\\.10\\.10\\.",
        end_keyword = "GigabitEthernet0/0/0",
        regex = true
    }
}
	[
"routing_table"
]
ip_route_comparison = { 
    flexible_pattern = {
        start_keyword = "10\\.10\\.10\\.10/25",
        end_keyword = "GigabitEthernet0/0/0$",
        regex = true,
        escape_start_keyword = false  # 新しいオプション
    }
}
["show ip route"]
ip_route_comparison = { 
    flexible_pattern = {
        start_keyword = "D\\s+10\\.10\\.10\\.",
        end_keyword = "GigabitEthernet0/0/0$",
        regex = true,
        escape_start_keyword = false
    }
}
["show ip route"]
ip_route_comparison = { 
    flexible_pattern = {
        start_keyword = "D\\s+10\\.10\\.10\\.",
        end_keyword = "GigabitEthernet0/0/0",
        regex = true,
        escape_start_keyword = false,
        include_end_keyword = true  # 新しいオプション
    }
}
[
"show ip route"
]
ip_route_comparison = { 
    flexible_pattern = {
        ip_addresses = [
            "10.10.23.10/25",
            "10.10.24.10/25",
            "10.10.25.10/25"
        ],
        start_keyword = "D\\s+",
        end_keyword = "GigabitEthernet\\d+/\\d+/\\d+",
        regex = true,
        escape_start_keyword = false,
        include_end_keyword = true,
        ignore_time = true
    }
}
